---
title: "Publications"
---

*Full and up-to-date list also available on [Google Scholar](https://scholar.google.com/citations?user=mrRinzAAAAAJ&hl=en) and [ORCID](https://orcid.org/0000-0001-5587-4897).*

## 2026

- Das, C., Kunchala, R. K., Karumuri, R. K., Gandham, H., Paul, D., Dasari, H. P., & Hoteit, I. (2026).Unveiling the multiscale variability of atmospheric carbon dioxide (CO2) over the Arabian Peninsula using remote sensing observations.Atmospheric Research, 336, 108891. https://doi.org/10.1016/j.atmosres.2026.108891

## 2025

- Das, C., Chatterjee, A., Kunchala, R. K., & Liu, J. (2025). Regional fire dynamics and its contributions to carbon flux variability in South Asia. Environmental Research Letters, 19(4), Article 046005. https://doi.org/10.1088/1748-9326/ae18e6

- Das, C., Kunchala, R. K., Patra, P. K., Chandra, N., Ishijima, K., & Machida, T. (2025). An assessment of CO2 transport model simulations using surface, aircraft and satellite data (2015–2021). Atmospheric Environment. https://doi.org/10.1016/j.atmosenv.2025.121754

## 2023

- Das, C., Kunchala, R. K., Chandra, N., Chhabra, A., & Pandya, M. R. (2023). Characterising the regional XCO2 variability and its association with ENSO over India inferred from GOSAT and OCO-2. Science of the Total Environment, 166176. https://doi.org/10.1016/j.scitotenv.2023.166176

## 2022

- Das, C., Kunchala, R. K., Chandra, N., Chmura, L., Necki, J., Patra, P. K. (2022). Meridional propagation of carbon dioxide (CO2) growth rate and flux anomalies from the tropics due to ENSO. Geophysical Research Letters, 49, e2022GL100105. https://doi.org/10.1029/2022GL100105

---